### ISSUE TITLE
Add the ability to check if Ptr is null.

### ISSUE THREAD

**Issue by i10416** [markehammons/slinc#157]

**Comment by markehammons** [comment]
I don't actually have a good way of doing that at present. I need to add a Ptr.isNull method.

**Comment by i10416** [comment]
Thanks!

**Comment by markehammons** [comment]
This is now finished. You can check if a Ptr is null via the following code: `ptr == Null[A]`. You can drop the `[A]` to get null as a `Ptr[Nothing]`. Ptr equality has been defined as equivalence of address and offset of two Ptr instances.
