### ISSUE TITLE
va_list support

### ISSUE THREAD

**Issue by rcano** [markehammons/slinc#30]
Would supporting this even be possible? In trying to interface with libevdev, one of their most useful apis, logging, requires va_lists

**Comment by markehammons** [comment]
I will give it a shot in January. In theory, it should be possible, but it may not be compatible with my current designs (in which case I have to modify the design of slinc). Sorry for the late response, I've been moving and life has been hectic recently.

**Comment by markehammons** [comment]
Hey @rcano can you tell me the specific API you're trying to interface with? Specifically the function you're trying to bind to.

**Comment by rcano** [comment]
Here it is https://www.freedesktop.org/software/libevdev/doc/latest/group__logging.html#gaa60be86b83b3a6c82d8e536ba89ff955

**Comment by markehammons** [comment]
Hi @rcano. It's been a long time. I've got good and bad news for you. The good news is that I'm nearly done with this feature, and it should be available as part of the release I'm making on Saturday or Sunday this week. 

The bad news, however, is that I must mark this feature `@experimental`. `[va_list](https://github.com/openjdk/panama-foreign/pull/763)` support has been slated for removal from the foreign api come java 21, and since I depend on the foreign api, I will probably drop them or

**Comment by markehammons** [comment]
It may be possible to add support for va_list to java 21, but this will be
- hard to test
- hard to fix
I have considered getting an aws m1 instance for testing Slinc on aarch64, and I'd need it even more for testing and bugfixing va_list support that I roll on my own. Let's see.

**Comment by markehammons** [comment]
I've created an issue to track #166, substituting java foreign's implementation of VaList for a home-made one in Slinc.

**Comment by rcano** [comment]
This is indeed unfortunate. There's a chicken-egg scenario with va_list going by that mailing-list discussion.
If the feature is implemented, and tested with some apis, that could work as use-cases as they are requesting on the mailing-list, for future consideration to re-add it. It's okay if you don't merge it to the main branch and release it, just keep it in a branch and I can pull and test.

**Comment by markehammons** [comment]
I've merged the work needed, and I've tested your usecase. For your usecase, I didn't have much trouble with Java 17, but in other cases I had bugs with Java 17 so I'd suggest you test this stuff on Java 19. Version 0.4.0 will have this available, and will be published saturday.
